export const events: Record<string, string> = {
    ACCOUNTS_IMPORT: 'ACCOUNTS_IMPORT',
    ACCOUNTS_REMOVE: 'ACCOUNTS_REMOVE',
    ANCHOR_FACTORY_RESET: 'ANCHOR_FACTORY_RESET',
    SESSION_ADD: 'SESSION_ADD',
    SESSION_ADD_IDENTITY: 'SESSION_ADD_IDENTITY',
    SESSION_CONFIG: 'SESSION_CONFIG',
    SESSION_REMOVE: 'SESSION_REMOVE',
    SIGNER_IMPORT_BY_PRIVATE_KEY: 'SIGNER_IMPORT_BY_PRIVATE_KEY',
    SIGNER_LIST_KEYS: 'SIGNER_LIST_KEYS',
    SIGNER_LOAD_STORAGE: 'SIGNER_LOAD_STORAGE',
    SIGNER_LOCK: 'SIGNER_LOCK',
    SIGNER_REMOVE_BY_PUBLIC_KEY: 'SIGNER_REMOVE_BY_PUBLIC_KEY',
    SIGNER_SET_PASSWORD: 'SIGNER_SET_PASSWORD',
    SIGNER_SIGN_DIGEST: 'SIGNER_SIGN_DIGEST',
    SIGNER_SIGN_TRANSACTION: 'SIGNER_SIGN_TRANSACTION',
    SIGNER_UNLOCK: 'SIGNER_UNLOCK',
    SIGNER_VALIDATE_PASSWORD: 'SIGNER_VALIDATE_PASSWORD',
    SIGNING_REQUEST_CANCELLED: 'SIGNING_REQUEST_CANCELLED',
    SIGNING_REQUEST_EXAMPLE: 'SIGNING_REQUEST_EXAMPLE',
}

export default events
